#[cfg(not(target_os = "ios"))]
use super::build::build_measurement_input_stream;
#[cfg(not(target_os = "ios"))]
use super::build::build_measurement_output_stream;
#[cfg(not(target_os = "ios"))]
use super::choose::choose_measurement_input_config;
#[cfg(not(target_os = "ios"))]
use super::choose::choose_measurement_output_config;
use super::consts::CANCELLED_ERR;
#[cfg(not(target_os = "ios"))]
use super::misc::actionable_capture_error;
#[cfg(not(target_os = "ios"))]
use super::misc::drain_capture;
use crate::signals::*;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

/// Cooperative cancellation flag for recording-side capture loops.
///
/// Callers create one with `CancelFlag::default()` (or
/// `Arc::new(AtomicBool::new(false))`) and store it alongside the running
/// task. Setting the flag to `true` from any thread asks the recorder to
/// stop the in-progress playback + capture as soon as the next stability
/// poll fires (worst-case ~50 ms latency). The recorder returns
/// `Err("cancelled")` so callers can distinguish user-cancellation from
/// real failures.
pub type CancelFlag = Arc<AtomicBool>;

#[inline]
pub(super) fn cancel_requested(cancel: Option<&CancelFlag>) -> bool {
    cancel.is_some_and(|c| c.load(Ordering::Relaxed))
}

/// Parameters for signal generation
#[derive(Debug, Clone)]
pub enum SignalParams {
    Tone {
        freq: f32,
        amp: f32,
    },
    TwoTone {
        freq1: f32,
        amp1: f32,
        freq2: f32,
        amp2: f32,
    },
    Sweep {
        start_freq: f32,
        end_freq: f32,
        amp: f32,
    },
    /// Octave-scaled sweep with pre/post silence windows (GD-Opt v2 §2.7).
    ///
    /// The sweep itself is generated by [`gen_log_sweep_octave_scaled`]; silence
    /// windows are prepended and appended so the noise floor and room decay can
    /// be measured from the same recording file.
    OctaveSweep {
        start_freq: f32,
        end_freq: f32,
        amp: f32,
        /// Seconds per octave below 100 Hz (default 3.0, clamped [1.0..10.0]).
        bass_octave_duration_s: f32,
        /// Silence window before the sweep in seconds (default 2.0).
        pre_silence_s: f32,
        /// Silence window after the sweep in seconds (default ≈ RT60 + 1.0).
        post_silence_s: f32,
    },
    Noise {
        amp: f32,
    },
    Mls {
        order: u8,
        amp: f32,
    },
    Dirac {
        amp: f32,
    },
}

/// Result of a delay probing session across all channels.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeDelayResults {
    /// Per-channel delay detection results
    pub channels: Vec<ProbeDelayChannelResult>,
    /// Sample rate used for probing
    pub sample_rate: u32,
    /// Computed alignment delays in ms (to add to each channel)
    pub alignment_delays_ms: Vec<f64>,
}

/// Delay probe result for a single channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeDelayChannelResult {
    /// Channel name (e.g. "L", "R", "C")
    pub channel_name: String,
    /// Channel output index
    pub channel_index: usize,
    /// Detected arrival time in ms
    pub arrival_ms: f64,
    /// Relative gain in dB
    pub gain_db: f64,
    /// Detection confidence (SNR in dB)
    pub snr_db: f64,
}

/// Output of [`play_per_channel_and_record_mono`]: the raw mono mic
/// recording plus everything a caller needs to slice per-channel
/// segments at the recording's sample rate.
#[cfg(not(target_os = "ios"))]
#[derive(Debug)]
pub(super) struct PlayPerChannelOutput {
    /// Mono mic samples at `input_sr`. Length is determined by how
    /// long the playback + tail ran on the host audio system.
    pub(super) recorded: Vec<f32>,
    /// Optional parallel loopback capture (same length / sample rate
    /// as `recorded`). Populated when the caller passed a
    /// `loopback_input_channel`. Used by the bass-anchor lock-in path
    /// to subtract source-side delay / clock skew from the per-channel
    /// phase reading.
    pub(super) loopback_recorded: Option<Vec<f32>>,
    /// Sample rate the mic actually captured at (may differ from the
    /// requested playback `sample_rate` when cpal had to negotiate).
    pub(super) input_sr: u32,
    /// Per-channel segment start offset in `recorded`, at `input_sr`.
    /// `analysis_offsets[i]` is the first sample of channel `i`'s
    /// stimulus response.
    pub(super) analysis_offsets: Vec<usize>,
    /// Length of one channel's signal at `input_sr`. Slicing
    /// `&recorded[offset..offset + analysis_signal_samples]` isolates
    /// the full response of one channel (including room decay up to
    /// the end of the next silence window).
    pub(super) analysis_signal_samples: usize,
    /// Length of the silence gap at `input_sr`. Useful for callers
    /// that need noise-floor estimation from pre-signal bins.
    pub(super) analysis_silence_samples: usize,
}

#[cfg(not(target_os = "ios"))]
#[derive(Debug, Clone, Copy)]
pub(super) struct MeasurementOutputConfig {
    pub(super) channels: u16,
    pub(super) sample_rate: u32,
    pub(super) sample_format: cpal::SampleFormat,
}

#[cfg(not(target_os = "ios"))]
#[derive(Debug, Clone, Copy)]
pub(super) struct MeasurementInputConfig {
    pub(super) channels: u16,
    pub(super) sample_rate: u32,
    pub(super) sample_format: cpal::SampleFormat,
}

/// Shared playback + capture scaffolding for both
/// [`probe_channel_delays_core`] (wideband delay probe) and
/// [`run_bass_anchor_core`] (bass anchor tone burst).
///
/// Builds a playback buffer of the form
///   `[silence][ch0_signal][silence][ch1_signal]...[silence]`,
/// writes it directly to a CPAL output stream, records from the mic
/// while it plays, waits for the recording to settle, and returns the
/// raw mono recording together with per-channel analysis offsets scaled
/// to the mic's actual sample rate.
///
/// Analysis is the caller's responsibility — this helper intentionally
/// knows nothing about cross-correlation, DFTs, or any stimulus-
/// specific interpretation of the recording.
///
/// `log_tag` is prefixed into log lines so probe and bass-anchor
/// captures remain distinguishable in noisy system logs.
#[cfg(not(target_os = "ios"))]
#[allow(clippy::too_many_arguments)]
pub(super) fn play_per_channel_and_record_mono(
    channel_indices: &[u16],
    sample_rate: u32,
    signal: &[f32],
    silence_duration_ms: f32,
    output_device_name: Option<&str>,
    input_device_name: Option<&str>,
    input_channel: u16,
    loopback_input_channel: Option<u16>,
    log_tag: &str,
    cancel: Option<&CancelFlag>,
) -> Result<PlayPerChannelOutput, String> {
    use cpal::traits::{DeviceTrait, HostTrait, StreamTrait};
    use std::sync::atomic::{AtomicUsize, Ordering as AtomicOrdering};
    use std::thread::sleep;
    use std::time::Duration;

    if cancel_requested(cancel) {
        return Err(CANCELLED_ERR.to_string());
    }

    let num_channels = channel_indices.len();
    if num_channels == 0 {
        return Err(format!("[{log_tag}] No channels to capture"));
    }
    if signal.is_empty() {
        return Err(format!("[{log_tag}] Empty stimulus signal"));
    }

    let signal_samples = signal.len();
    let silence_samples = (silence_duration_ms / 1000.0 * sample_rate as f32) as usize;

    // --- Output device discovery + hardware channel count ---
    let host = cpal::default_host();
    let output_device = if let Some(dev_name) = output_device_name {
        crate::devices::find_device(&host, dev_name, false).map_err(|e| {
            actionable_capture_error(&format!("[{log_tag}] Output device not usable"), &e)
        })?
    } else {
        host.default_output_device().ok_or_else(|| {
            actionable_capture_error(
                &format!("[{log_tag}]"),
                &"No default output device available",
            )
        })?
    };

    // Use a direct CPAL stream with at least enough channels to address
    // the highest target output. This keeps measurement routing as raw
    // physical-channel writes and avoids file-decoder channel-layout
    // interpretation or normal playback downmix/upmix paths.
    let supported_output_configs: Vec<_> = output_device
        .supported_output_configs()
        .map_err(|e| {
            actionable_capture_error(
                &format!("[{log_tag}] Failed to get supported output configs"),
                &e,
            )
        })?
        .collect();
    let device_max_channels = supported_output_configs
        .iter()
        .map(|config| config.channels() as usize)
        .max()
        .unwrap_or(2);

    // channel_indices is non-empty (checked above).
    let max_target_channel = channel_indices.iter().map(|&c| c as usize).max().unwrap();
    if max_target_channel >= device_max_channels {
        return Err(format!(
            "[{log_tag}] Channel {} exceeds hardware output count {}",
            max_target_channel, device_max_channels
        ));
    }
    let hardware_channels = max_target_channel + 1;
    let output_config = choose_measurement_output_config(
        &supported_output_configs,
        hardware_channels as u16,
        sample_rate,
    )?;
    let playback_channels = output_config.channels as usize;

    // --- Build the playback buffer ---
    let segment_len = silence_samples + signal_samples;
    let total_frames = silence_samples + num_channels * segment_len;

    let mut per_channel: Vec<Vec<f32>> = (0..playback_channels)
        .map(|_| vec![0.0_f32; total_frames])
        .collect();

    for (i, &ch_idx) in channel_indices.iter().enumerate() {
        let frame_offset = silence_samples + i * segment_len;
        for (j, &s) in signal.iter().enumerate() {
            per_channel[ch_idx as usize][frame_offset + j] = s;
        }
        log::debug!(
            "[{log_tag}] Channel {} at frame {}, output ch {}",
            i,
            frame_offset,
            ch_idx
        );
    }

    let playback = Arc::new(interleave_per_channel(&per_channel));
    let playback_cursor = Arc::new(AtomicUsize::new(0));
    log::info!(
        "[{log_tag}] Prepared direct {}ch playback stream ({} target ch): {} frames ({:.2}s)",
        playback_channels,
        hardware_channels,
        total_frames,
        total_frames as f64 / sample_rate as f64
    );

    // --- Input device + stream setup ---
    let input_device = if let Some(dev_name) = input_device_name {
        crate::devices::find_device(&host, dev_name, true).map_err(|e| {
            actionable_capture_error(&format!("[{log_tag}] Input device not usable"), &e)
        })?
    } else {
        host.default_input_device().ok_or_else(|| {
            actionable_capture_error(
                &format!("[{log_tag}]"),
                &"No default input device available",
            )
        })?
    };

    if let Some(lb) = loopback_input_channel
        && lb == input_channel
    {
        return Err(format!(
            "[{log_tag}] Loopback input channel {lb} must differ from mic input channel {input_channel}"
        ));
    }

    let min_input_ch =
        (input_channel as usize).max(loopback_input_channel.map(|c| c as usize).unwrap_or(0)) + 1;
    let default_input_config = input_device.default_input_config().map_err(|e| {
        actionable_capture_error(
            &format!("[{log_tag}] Failed to get default input config"),
            &e,
        )
    })?;
    let supported_input_configs: Vec<_> = input_device
        .supported_input_configs()
        .map(|configs| configs.collect())
        .unwrap_or_else(|e| {
            log::warn!("[{log_tag}] Failed to enumerate supported input configs: {e}");
            Vec::new()
        });
    let input_config =
        choose_measurement_input_config(&supported_input_configs, min_input_ch as u16, sample_rate)
            .unwrap_or_else(|| MeasurementInputConfig {
                channels: default_input_config.channels(),
                sample_rate: default_input_config.sample_rate(),
                sample_format: default_input_config.sample_format(),
            });
    if (input_config.channels as usize) < min_input_ch {
        return Err(format!(
            "[{log_tag}] Input channel {} exceeds capture input count {}",
            min_input_ch - 1,
            input_config.channels
        ));
    }
    let hw_input_ch = input_config.channels as usize;
    let input_sr = input_config.sample_rate;

    // Derive analysis offsets at the mic's actual sample rate so a
    // downstream mismatch (cpal negotiated a different rate than we
    // asked for) does not leak into per-channel segment slicing.
    let analysis_silence_samples = (silence_duration_ms / 1000.0 * input_sr as f32) as usize;
    let analysis_signal_samples =
        ((signal_samples as f64 * input_sr as f64) / sample_rate as f64).round() as usize;
    let analysis_segment_len = analysis_silence_samples + analysis_signal_samples;
    let analysis_offsets: Vec<usize> = (0..num_channels)
        .map(|i| analysis_silence_samples + i * analysis_segment_len)
        .collect();

    let input_stream_config = cpal::StreamConfig {
        channels: hw_input_ch as u16,
        sample_rate: input_sr,
        buffer_size: cpal::BufferSize::Default,
    };
    // Mic + optional loopback are pushed into one SPSC ring as a pair, so
    // they stay exactly in lock-step without locking inside the input callback.
    let expected_input_samples = ((total_frames as f64 * input_sr as f64 / sample_rate as f64)
        as usize)
        + (input_sr as usize / 2);
    let (capture_producer, mut capture_consumer) =
        rtrb::RingBuffer::<(f32, f32)>::new(expected_input_samples.max(1024));
    let capture_count = Arc::new(AtomicUsize::new(0));
    let capture_count_callback = Arc::clone(&capture_count);
    let capture_overruns = Arc::new(AtomicUsize::new(0));
    let capture_overruns_callback = Arc::clone(&capture_overruns);
    let loopback_ch_idx = loopback_input_channel.map(|c| c as usize);
    let input_ch_idx = input_channel as usize;
    let hw_ch = hw_input_ch;

    let input_stream = build_measurement_input_stream(
        &input_device,
        &input_stream_config,
        input_config.sample_format,
        capture_producer,
        capture_count_callback,
        capture_overruns_callback,
        hw_ch,
        input_ch_idx,
        loopback_ch_idx,
        log_tag,
    )?;

    input_stream.play().map_err(|e| {
        actionable_capture_error(&format!("[{log_tag}] Failed to start input stream"), &e)
    })?;
    sleep(Duration::from_millis(100));

    // --- Start direct playback ---
    if cancel_requested(cancel) {
        std::mem::drop(input_stream);
        return Err(CANCELLED_ERR.to_string());
    }
    let output_stream = build_measurement_output_stream(
        &output_device,
        &output_config,
        playback.clone(),
        playback_cursor.clone(),
        log_tag,
    )?;
    output_stream.play().map_err(|e| {
        actionable_capture_error(&format!("[{log_tag}] Failed to start output stream"), &e)
    })?;

    // Wait for playback to finish — same stability-loop pattern both
    // original functions used. Honors `cancel` between polls so a UI
    // stop button propagates with at most ~50 ms of latency.
    let expected_duration = total_frames as f64 / sample_rate as f64;
    let total_wait = Duration::from_secs_f64(expected_duration + 3.0);
    let check_interval = Duration::from_millis(50);
    let mut elapsed = Duration::ZERO;
    let mut last_count = 0_usize;
    let mut stable = 0_u32;
    let mut cancelled = false;
    while elapsed < total_wait {
        sleep(check_interval);
        elapsed += check_interval;
        if cancel_requested(cancel) {
            cancelled = true;
            log::info!("[{log_tag}] Cancellation requested — aborting capture");
            break;
        }
        let played = playback_cursor.load(AtomicOrdering::Relaxed);
        let count = capture_count.load(AtomicOrdering::Relaxed);
        if count == last_count && count > 0 {
            stable += 1;
            if stable >= 3 && played >= playback.len() {
                break;
            }
        } else {
            stable = 0;
        }
        last_count = count;
        if played >= playback.len() && elapsed >= Duration::from_secs_f64(expected_duration + 0.2) {
            break;
        }
    }

    // Tear everything down in playback → input-stream → sleep order.
    // Skipping the sleep reliably leaves the audio device busy for the
    // next consecutive run. On cancel, skip the tail-capture sleep so
    // the UI gets snappy feedback.
    if !cancelled {
        sleep(Duration::from_millis(500));
    }
    std::mem::drop(output_stream);
    std::mem::drop(input_stream);
    sleep(Duration::from_millis(500));

    if cancelled {
        return Err(CANCELLED_ERR.to_string());
    }

    let capture_pairs = drain_capture(
        &mut capture_consumer,
        capture_count.load(AtomicOrdering::Relaxed),
    );
    let mut recorded = Vec::with_capacity(capture_pairs.len());
    let mut loopback_recorded =
        loopback_input_channel.map(|_| Vec::with_capacity(capture_pairs.len()));
    for (mic, loopback) in capture_pairs {
        recorded.push(mic);
        if let Some(lb) = loopback_recorded.as_mut() {
            lb.push(loopback);
        }
    }
    let dropped_samples = capture_overruns.load(AtomicOrdering::Relaxed);
    if dropped_samples > 0 {
        log::warn!(
            "[{log_tag}] Dropped {} input frames because the capture ring buffer filled",
            dropped_samples
        );
    }
    log::info!(
        "[{log_tag}] Recorded {} samples ({:.2}s) at {} Hz",
        recorded.len(),
        recorded.len() as f64 / input_sr as f64,
        input_sr
    );

    let rec_peak = recorded.iter().map(|s| s.abs()).fold(0.0_f32, f32::max);
    if rec_peak < 1e-4 {
        return Err(format!(
            "[{log_tag}] Recording appears silent (peak {:.6}). Check mic, input channel, and output device availability.",
            rec_peak
        ));
    }

    if let Some(ref lb) = loopback_recorded {
        // Mic and loopback are pushed in lock-step under the same
        // Mutex; if they diverge here something deeper went wrong
        // (callback panic, cpal frame anomaly) and we must refuse
        // rather than silently truncate downstream.
        if lb.len() != recorded.len() {
            return Err(format!(
                "[{log_tag}] Mic/loopback length mismatch: mic={}, loopback={} — capture corrupted",
                recorded.len(),
                lb.len()
            ));
        }
        let lb_peak = lb.iter().map(|s| s.abs()).fold(0.0_f32, f32::max);
        log::info!(
            "[{log_tag}] Loopback captured {} samples, peak {:.4}",
            lb.len(),
            lb_peak
        );
    }

    Ok(PlayPerChannelOutput {
        recorded,
        loopback_recorded,
        input_sr,
        analysis_offsets,
        analysis_signal_samples,
        analysis_silence_samples,
    })
}

#[derive(Debug, Clone, Copy)]
pub(super) struct DirectArrivalPeak {
    pub(super) peak_sample_refined: f64,
    pub(super) peak_value: f32,
}

pub(super) fn pick_direct_arrival_from_envelope(
    envelope: &[f32],
    sample_rate: u32,
    max_search_samples: usize,
) -> Option<DirectArrivalPeak> {
    if envelope.len() < 3 || sample_rate == 0 || max_search_samples < 3 {
        return None;
    }

    let causal_len = (envelope.len() / 2).min(max_search_samples).max(3);
    let search = &envelope[..causal_len];
    let strongest = search.iter().copied().fold(0.0_f32, f32::max);
    if strongest <= 1e-10 {
        return None;
    }

    let mut sorted = search.to_vec();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let median = sorted[sorted.len() / 2].max(1e-10);
    let p90 = sorted[((sorted.len() as f32 * 0.90) as usize).min(sorted.len() - 1)];

    // Prefer the first direct-arrival peak over later room/modal energy.
    // The absolute threshold rejects the correlation noise floor; the
    // relative threshold still allows a direct sound that is noticeably
    // weaker than a later reflection.
    let threshold = (median * 12.0).max(p90 * 2.0).max(strongest * 0.08);
    let lookahead = ((sample_rate as f32 * 0.003).round() as usize).clamp(8, 256);

    let mut i = 1_usize;
    while i + 1 < causal_len {
        if search[i] < threshold {
            i += 1;
            continue;
        }

        let end = (i + lookahead).min(causal_len - 1);
        let mut peak = i;
        let mut peak_value = search[i];
        for (j, &value) in search.iter().enumerate().take(end + 1).skip(i) {
            if value > peak_value {
                peak = j;
                peak_value = value;
            }
        }

        if peak > 0 && peak + 1 < causal_len {
            let y_prev = search[peak - 1] as f64;
            let y_peak = search[peak] as f64;
            let y_next = search[peak + 1] as f64;
            let denom = 2.0 * (2.0 * y_peak - y_prev - y_next);
            let peak_sample_refined = if denom.abs() > 1e-12 {
                peak as f64 + (y_prev - y_next) / denom
            } else {
                peak as f64
            };
            return Some(DirectArrivalPeak {
                peak_sample_refined,
                peak_value,
            });
        }

        return Some(DirectArrivalPeak {
            peak_sample_refined: peak as f64,
            peak_value,
        });
    }

    None
}

/// Result of a bass-anchor capture across all channels.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BassAnchorResults {
    /// Per-channel phase + quality.
    pub channels: Vec<BassAnchorChannelResult>,
    /// Input sample rate used for the analysis (may differ from
    /// `requested_sample_rate` if cpal negotiated a different rate).
    pub sample_rate: u32,
    /// Centre frequency of the steady-state tone in Hz.
    pub bass_freq_hz: f32,
    /// Total tone length in seconds (steady portion + fades).
    pub bass_duration_s: f32,
}

/// Per-channel bass-anchor result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BassAnchorChannelResult {
    pub channel_name: String,
    pub channel_index: usize,
    /// Reported phase of the bass tone, degrees in (−180°, 180°],
    /// sin-referenced. When a loopback channel is recorded this is the
    /// loopback-corrected acoustic phase
    /// (`phase_mic − phase_loopback`); otherwise it is the raw mic
    /// phase. See `bass_anchor_loopback_phase_deg` for the raw
    /// loopback reference value.
    pub bass_anchor_phase_deg: f64,
    /// Linear magnitude of the lock-in I/Q estimator at `bass_freq_hz`
    /// on the mic — SNR proxy.
    pub bass_anchor_magnitude: f64,
    /// Circular standard deviation of phase across the sub-window
    /// lock-in estimates, in degrees. Combines the mic-side spread
    /// with the loopback-side spread in quadrature when a loopback
    /// channel is present. Advisory threshold is 20° (§2.8 of the
    /// GD-Opt v2 plan, `docs/gd_opt_v2_plan.md` in the autoeq repo).
    pub bass_anchor_stability_deg: f64,
    /// Raw loopback reference phase in degrees (sin-referenced). `None`
    /// when no loopback channel was recorded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bass_anchor_loopback_phase_deg: Option<f64>,
    /// Magnitude-squared coherence γ² ∈ [0, 1] between the mic and
    /// loopback per-window phasors at `bass_freq_hz`:
    ///   γ² = |⟨X · conj(Y)⟩|² / (⟨|X|²⟩ · ⟨|Y|²⟩)
    /// γ²=1 → mic and loopback are linearly related (clean acoustic +
    /// electronic chain); γ²→0 → mic is dominated by uncorrelated
    /// noise. The conventional QA threshold is γ² > 0.9. `None` when
    /// no loopback channel was recorded.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bass_anchor_coherence: Option<f64>,
}

/// Pure analysis: given the mono recording from a bass-anchor session
/// and its layout, return per-channel phase results without touching
/// cpal. Used by the replay-driven tests and by any future offline
/// re-analysis tool.
///
/// `channel_starts` lists the sample index in `recorded` where each
/// channel's tone segment begins (mic-side). `tone_samples` is the
/// length of the steady-state tone at the mic's sample rate. When
/// `loopback_recorded` is `Some`, the same `channel_starts` /
/// `tone_samples` slice the loopback for per-channel reference phase
/// extraction; the reported `bass_anchor_phase_deg` becomes
/// `phase_mic − phase_loopback`, wrapped to (−180°, 180°].
#[allow(clippy::too_many_arguments)]
pub fn analyze_bass_anchor_recording(
    recorded: &[f32],
    loopback_recorded: Option<&[f32]>,
    channel_names: &[String],
    channel_indices: &[u16],
    sample_rate: u32,
    bass_freq_hz: f32,
    bass_duration_s: f32,
    num_windows: u16,
    channel_starts: &[usize],
    tone_samples: usize,
) -> Result<BassAnchorResults, String> {
    if channel_names.len() != channel_starts.len() || channel_names.len() != channel_indices.len() {
        return Err("channel_names / channel_indices / channel_starts length mismatch".to_string());
    }
    if let Some(lb) = loopback_recorded
        && lb.len() != recorded.len()
    {
        // Mic and loopback are pushed under one Mutex per cpal callback,
        // so they should always have identical lengths. A divergence
        // here means either the cpal callback dropped frames on one
        // channel only, or a caller fed us a mis-sized loopback slice
        // — both invalidate the per-channel offset slicing below.
        return Err(format!(
            "Loopback length {} does not match mic length {} — refusing to analyse with desynced inputs",
            lb.len(),
            recorded.len()
        ));
    }
    let nw = num_windows.max(1) as usize;

    let mut channels = Vec::with_capacity(channel_names.len());
    for (i, (&start, name)) in channel_starts.iter().zip(channel_names.iter()).enumerate() {
        let end = (start + tone_samples).min(recorded.len());
        if start >= recorded.len() {
            return Err(format!(
                "Channel {} start {} exceeds recording length {}",
                name,
                start,
                recorded.len()
            ));
        }
        let segment = &recorded[start..end];
        let mic_phasors =
            math_audio_dsp::signals::tone_phase_phasors(segment, bass_freq_hz, sample_rate, nw);
        let mic = math_audio_dsp::signals::aggregate_tone_phase(&mic_phasors);

        let (phase_deg, stability_deg, loopback_phase_deg, coherence) = match loopback_recorded {
            Some(lb) => {
                if start >= lb.len() {
                    return Err(format!(
                        "Channel {} start {} exceeds loopback length {}",
                        name,
                        start,
                        lb.len()
                    ));
                }
                let lb_end = (start + tone_samples).min(lb.len());
                let lb_segment = &lb[start..lb_end];
                if lb_end - start != end - start {
                    return Err(format!(
                        "Channel {} loopback slice length {} differs from mic slice length {}",
                        name,
                        lb_end - start,
                        end - start
                    ));
                }
                let lb_phasors = math_audio_dsp::signals::tone_phase_phasors(
                    lb_segment,
                    bass_freq_hz,
                    sample_rate,
                    nw,
                );
                let lb_res = math_audio_dsp::signals::aggregate_tone_phase(&lb_phasors);
                let mut diff = mic.phase_deg - lb_res.phase_deg;
                while diff > 180.0 {
                    diff -= 360.0;
                }
                while diff <= -180.0 {
                    diff += 360.0;
                }
                // Combined uncertainty: mic and loopback per-window
                // phase variances add in quadrature (independent
                // measurements).
                let combined_std =
                    (mic.stability_deg.powi(2) + lb_res.stability_deg.powi(2)).sqrt();
                // True magnitude-squared coherence between mic and
                // loopback I/Q per sub-window. γ²=1 → linearly related
                // (clean acoustic + electronic chain); γ²→0 → mic is
                // dominated by noise uncorrelated with the playback.
                let coherence =
                    math_audio_dsp::signals::phasor_coherence(&mic_phasors, &lb_phasors);
                (diff, combined_std, Some(lb_res.phase_deg), coherence)
            }
            None => (mic.phase_deg, mic.stability_deg, None, None),
        };

        channels.push(BassAnchorChannelResult {
            channel_name: name.clone(),
            channel_index: channel_indices[i] as usize,
            bass_anchor_phase_deg: phase_deg,
            bass_anchor_magnitude: mic.magnitude,
            bass_anchor_stability_deg: stability_deg,
            bass_anchor_loopback_phase_deg: loopback_phase_deg,
            bass_anchor_coherence: coherence,
        });
    }

    Ok(BassAnchorResults {
        channels,
        sample_rate,
        bass_freq_hz,
        bass_duration_s,
    })
}

/// Result of a single SPL-calibration capture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SplCalibrationResult {
    /// Sample rate the mic captured at (Hz).
    pub sample_rate: u32,
    /// Peak absolute sample value observed on the mic during the tone
    /// (the stable window — excludes attack/release).
    pub peak_sample_level: f32,
    /// RMS sample value over the stable window. More noise-robust
    /// than the peak and preferred when authoring SplCalibration.
    pub rms_sample_level: f32,
    /// Frequency of the tone that was played, echoed back for audit.
    pub reference_freq_hz: f32,
    /// Playback output channel index used during the capture.
    pub output_channel: u16,
}

/// Device information for recording metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeviceInfo {
    pub device_id: String,
    pub device_name: String,
    pub num_channels: usize,
}

/// Information about a single channel's recording
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelRecordingInfo {
    /// Channel index (0-based)
    pub channel_index: usize,
    /// Channel name (e.g., "L", "R", "C")
    pub channel_name: String,
    /// Interface output channel used for playback
    pub output_channel: usize,
    /// Interface input channel used for recording
    pub input_channel: usize,
    /// Path to WAV file (relative to session directory)
    pub wav_path: String,
    /// Path to CSV file with analysis data (relative to session directory)
    pub csv_path: String,
    /// Whether recording succeeded
    pub success: bool,
    /// Error message if recording failed
    pub error: Option<String>,
    /// Per-channel microphone calibration file path
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mic_calibration_path: Option<String>,
}
