// SOTF Audio FFI - Auto-generated C header
// DO NOT EDIT - Generated by cbindgen

#ifndef SOTF_AUDIO_FFI_H
#define SOTF_AUDIO_FFI_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by FFI functions
 */
typedef enum PluginError {
  Success = 0,
  InvalidHandle = -1,
  InvalidParameter = -2,
  NullPointer = -3,
  InvalidUtf8 = -4,
  PluginCreationFailed = -5,
  ProcessingFailed = -6,
  InitializationFailed = -7,
  InvalidConfig = -8,
  UnsupportedFeature = -9,
  BufferTooSmall = -10,
  UnknownError = -99,
} PluginError;

/**
 * Host/packaging family that can consume this C ABI.
 */
typedef enum PluginFfiHostKind {
  Unknown = 0,
  AudioUnitV3 = 1,
  Vst3 = 2,
  SwiftPackage = 3,
} PluginFfiHostKind;

/**
 * ABI-visible note expression kinds for future AUv3/VST3 bridging.
 */
typedef enum PluginNoteExpressionKind {
  PitchBend = 1,
  Pressure = 2,
  Timbre = 3,
  Brightness = 4,
  Volume = 5,
  Pan = 6,
} PluginNoteExpressionKind;

/**
 * Thread-safe parameter value cache using atomics.
 *
 * Each parameter is stored as an `AtomicU64` holding the bit representation
 * of an `f64` value. Reads and writes use `Relaxed` ordering since we only
 * need eventual consistency for UI display (no ordering constraints).
 *
 * Metadata (name, unit, min, max, default) is set once at creation and never
 * changes — no atomics needed for those fields.
 */
typedef struct AtomicParamCache AtomicParamCache;

/**
 * Opaque handle to a plugin instance.
 *
 * This is passed to Swift/Objective-C code and must not be dereferenced
 * outside of Rust. Use `plugin_*` functions to interact with it.
 *
 * # Ownership and lifetime
 *
 * A `PluginHandle` is created by [`plugin_create`] and owned by the caller.
 * The handle must be released exactly once with [`plugin_destroy`]; after
 * that it is invalid to use the pointer for any other call.
 *
 * The handle owns the plugin instance, the parameter map, the output-event
 * queues, and the channel-count metadata recorded at creation time. All
 * pointers returned into C memory that are derived from a handle
 * (for example [`plugin_get_parameter_info`], [`plugin_get_info_json`],
 * [`plugin_save_state`], or [`plugin_export_preset_json`]) are only valid
 * while the handle remains alive, unless the function documentation explicitly
 * says the returned pointer is owned by the caller and must be freed.
 */
typedef struct PluginHandle PluginHandle;

/**
 * C function pointer type for parameter writes.
 */
typedef void (*SetParamCallback)(void*, size_t, double);

/**
 * C function pointer type for parameter reset (to default).
 */
typedef void (*ResetParamCallback)(void*, size_t);

/**
 * Runtime-advertised FFI capabilities.
 */
typedef struct PluginFfiCapabilities {
  uint32_t abi_version;
  enum PluginFfiHostKind host_kind;
  bool supports_audio;
  bool supports_parameters;
  bool supports_state;
  bool supports_midi_input;
  bool supports_midi_output;
  bool supports_note_expression;
  bool supports_apple_au_v3;
  bool supports_ios_au_v3;
  bool supports_windows_vst3;
  bool supports_swift_package;
  bool supports_preset_documents;
} PluginFfiCapabilities;

/**
 * Preset/document metadata shared by AUv3 and SwiftPM hosts.
 */
typedef struct PluginPresetDocumentInfo {
  uint32_t schema_version;
  const char *ut_type;
  const char *file_extension;
  const char *mime_type;
  bool supports_full_state_for_document;
  bool supports_security_scoped_bookmarks;
} PluginPresetDocumentInfo;

/**
 * Windows/VST3 loader metadata for C#/Python hosts.
 */
typedef struct PluginVst3FfiDescriptor {
  uint32_t abi_version;
  uint8_t class_id[16];
  const char *component_name;
  const char *vendor;
  const char *sdk_version;
  const char *entrypoint;
  bool supports_com_factory;
  bool supports_audio_effects;
  bool supports_instruments;
  bool supports_midi_output;
  bool supports_note_expression;
} PluginVst3FfiDescriptor;

/**
 * Swift Package distribution metadata.
 */
typedef struct PluginSwiftPackageInfo {
  const char *package_name;
  const char *product_name;
  const char *target_name;
  const char *library_name;
  const char *umbrella_header;
  bool supports_staticlib;
  bool supports_xcframework;
} PluginSwiftPackageInfo;

/**
 * Raw MIDI event scheduled within a processing block.
 */
typedef struct PluginMidiEvent {
  size_t sample_offset;
  uint8_t data[3];
  uint8_t len;
} PluginMidiEvent;

/**
 * Per-note expression event scheduled within a processing block.
 */
typedef struct PluginNoteExpressionEvent {
  size_t sample_offset;
  int32_t note_id;
  uint8_t channel;
  uint8_t note;
  enum PluginNoteExpressionKind expression;
  double value;
} PluginNoteExpressionEvent;

/**
 * Parameter information exposed to AU host
 */
typedef struct ParameterInfo {
  /**
   * Unique parameter ID (e.g., "threshold_db")
   */
  const char *id;
  /**
   * Human-readable name (e.g., "Threshold")
   */
  const char *name;
  /**
   * Unit string (e.g., "Hz", "dB", "")
   */
  const char *unit;
  /**
   * Minimum value
   */
  double min_value;
  /**
   * Maximum value
   */
  double max_value;
  /**
   * Default value
   */
  double default_value;
  /**
   * Number of steps (0 = continuous)
   */
  uint32_t steps;
  /**
   * Whether this parameter uses logarithmic scaling
   */
  bool logarithmic;
} ParameterInfo;

/**
 * Create a new atomic parameter cache.
 *
 * The returned pointer is `Arc`-allocated. Consumers that reconstruct an `Arc`
 * (e.g. `gpui_au_create_with_plugin`) MUST use `Arc::from_raw`.
 * FFI read/write/destroy functions work with raw pointer dereference and are
 * compatible with both `Box` and `Arc` layout since they never free the header.
 */
struct AtomicParamCache *au_param_cache_create(size_t count);

/**
 * Write a denormalized parameter value into the cache.
 *
 * Called from Swift's `implementorValueObserver` on the AU main thread
 * whenever a parameter changes (from host automation, MIDI, or UI).
 */
void au_param_cache_write(struct AtomicParamCache *cache, size_t index, double value);

/**
 * Read a denormalized parameter value from the cache.
 */
double au_param_cache_read(const struct AtomicParamCache *cache, size_t index);

/**
 * Set metadata for a parameter in the cache.
 *
 * Called from Swift during initialization to populate parameter names,
 * units, and ranges from the AUParameterTree.
 */
void au_param_cache_set_meta(struct AtomicParamCache *cache,
                             size_t index,
                             const char *name,
                             const char *unit,
                             double min_value,
                             double max_value,
                             double default_value);

/**
 * Destroy a parameter cache.
 */
void au_param_cache_destroy(struct AtomicParamCache *cache);

/**
 * Create a GPUI AU context with a real plugin UI.
 *
 * Unlike `gpui_au_create` (which shows a placeholder), this function creates
 * an `AuHostState` that reads parameters from an `AtomicParamCache` and writes
 * them through callbacks to the AU `AUParameterTree` — fully thread-safe.
 *
 * # Safety
 * - `ns_view` must be a valid NSView pointer
 * - `plugin_type` must be a valid C string
 * - `param_cache` must be a valid pointer from `au_param_cache_create()`
 * - `set_param_cb` / `reset_param_cb` must be valid function pointers
 * - `cb_userdata` must remain valid for the lifetime of the returned context
 */
void *gpui_au_create_with_plugin(void *ns_view,
                                 float width,
                                 float height,
                                 float scale,
                                 const char *plugin_type,
                                 struct AtomicParamCache *param_cache,
                                 SetParamCallback set_param_cb,
                                 ResetParamCallback reset_param_cb,
                                 void *cb_userdata);

/**
 * Get the last error message.
 *
 * # Returns
 * * Pointer to a null-terminated C string, or `NULL` if no error has been set.
 * * The pointer points to thread-local storage that remains valid until the
 *   next FFI call on the same thread that may set an error. Copy the contents
 *   if you need it to outlive the next call.
 */
const char *plugin_get_last_error(void);

/**
 * Get the stable ABI version for this FFI surface.
 */
uint32_t plugin_ffi_abi_version(void);

/**
 * Get runtime capabilities for the current target.
 */
struct PluginFfiCapabilities plugin_ffi_capabilities(void);

/**
 * Get machine-readable platform and capability metadata as JSON.
 *
 * # Returns
 * * JSON string owned by the caller. It must be released with
 *   [`plugin_free_string`] when no longer needed.
 * * `NULL` on error.
 */
char *plugin_ffi_platform_info_json(void);

/**
 * Get preset document metadata for host file dialogs and AUv3 document state.
 *
 * The returned string pointers reference static, null-terminated C strings
 * with program lifetime. They must not be freed.
 */
struct PluginPresetDocumentInfo plugin_preset_document_info(void);

/**
 * Get Windows/VST3 FFI metadata for native language bindings.
 *
 * The returned string pointers reference static, null-terminated C strings
 * with program lifetime. They must not be freed.
 */
struct PluginVst3FfiDescriptor plugin_vst3_ffi_descriptor(void);

/**
 * Get Swift Package metadata for Xcode/SwiftPM integrations.
 *
 * The returned string pointers reference static, null-terminated C strings
 * with program lifetime. They must not be freed.
 */
struct PluginSwiftPackageInfo plugin_swift_package_info(void);

/**
 * Create a new plugin instance
 *
 * # Arguments
 * * `plugin_type` - Plugin type name (e.g., "EQ", "Compressor")
 * * `config_json` - JSON configuration string
 * * `sample_rate` - Sample rate in Hz
 * * `input_channels` - Number of input channels
 * * `output_channels` - Number of output channels
 *
 * # Returns
 * * Opaque plugin handle on success
 * * NULL on failure (check plugin_get_last_error())
 *
 * # Safety
 * * `plugin_type` and `config_json` must be valid, null-terminated UTF-8 C strings
 *   that remain readable for the duration of this call.
 * * The returned handle is owned by the caller and must be released with
 *   [`plugin_destroy`] exactly once. The pointer is invalid after that call.
 */
struct PluginHandle *plugin_create(const char *plugin_type,
                                   const char *config_json,
                                   uint32_t sample_rate,
                                   size_t input_channels,
                                   size_t output_channels);

/**
 * Destroy a plugin instance
 *
 * # Safety
 * * handle must be a valid pointer returned by plugin_create()
 * * handle must not be used after this call
 */
void plugin_destroy(struct PluginHandle *handle);

/**
 * Reset plugin state (clear buffers, reset filters)
 *
 * # Safety
 * * handle must be a valid pointer returned by plugin_create()
 */
int plugin_reset(struct PluginHandle *handle);

/**
 * Process audio samples
 *
 * # Arguments
 * * `handle` - Plugin handle
 * * `input` - Interleaved input samples [C0_F0, C1_F0, ..., C0_F1, C1_F1, ...]
 * * `output` - Interleaved output buffer (will be filled)
 * * `num_frames` - Number of frames to process
 *
 * # Returns
 * * 0 on success
 * * Error code on failure
 *
 * # Safety
 * * `handle` must be a valid plugin handle returned by [`plugin_create`] that
 *   has not been destroyed.
 * * `input` and `output` must be valid, properly aligned, non-overlapping
 *   buffers that remain valid for the duration of this call.
 * * `input` must contain at least `num_frames * input_channels` samples and
 *   `output` must have space for at least `num_frames * output_channels`
 *   samples, where `input_channels` and `output_channels` are the values
 *   passed to [`plugin_create`].
 * * This function is designed to be real-time safe (no allocations).
 */
int plugin_process(struct PluginHandle *handle,
                   const float *input,
                   float *output,
                   size_t num_frames);

/**
 * Process audio samples with incoming MIDI events.
 *
 * MIDI events are copied into a fixed stack buffer, then borrowed by
 * ProcessContext. No heap allocation occurs on the render path.
 *
 * # Safety
 * * `handle`, `input`, and `output` must satisfy the same contract as
 *   [`plugin_process`].
 * * `midi_events` must point to `midi_event_count` valid [`PluginMidiEvent`]
 *   structs and remain readable for the duration of this call. It may be
 *   `NULL` only when `midi_event_count` is `0`.
 */
int plugin_process_with_midi(struct PluginHandle *handle,
                             const float *input,
                             float *output,
                             size_t num_frames,
                             const struct PluginMidiEvent *midi_events,
                             size_t midi_event_count);

/**
 * Process audio with MIDI/note-expression input and output ABI slots.
 *
 * Incoming MIDI is bridged into ProcessContext. Queued MIDI output and Note
 * Expression events are copied into host-provided buffers without allocating
 * on the render path.
 *
 * # Safety
 * * `handle`, `input`, and `output` must satisfy the same contract as
 *   [`plugin_process`].
 * * `midi_input` must point to `midi_input_count` valid [`PluginMidiEvent`]
 *   structs and remain readable for the duration of this call. It may be
 *   `NULL` only when `midi_input_count` is `0`.
 * * `note_expression_input` must point to `note_expression_input_count` valid
 *   [`PluginNoteExpressionEvent`] structs and remain readable for the duration
 *   of this call. It may be `NULL` only when `note_expression_input_count` is `0`.
 * * If queued output events exist, `midi_output` and `note_expression_output`
 *   must be valid writable buffers with capacities matching the supplied
 *   `_capacity` values and remain writable for the duration of this call.
 * * `midi_output_count` and `note_expression_output_count` must be valid
 *   pointers to `usize` values that this call may write.
 */
int plugin_process_with_events(struct PluginHandle *handle,
                               const float *input,
                               float *output,
                               size_t num_frames,
                               const struct PluginMidiEvent *midi_input,
                               size_t midi_input_count,
                               const struct PluginNoteExpressionEvent *note_expression_input,
                               size_t note_expression_input_count,
                               struct PluginMidiEvent *_midi_output,
                               size_t _midi_output_capacity,
                               size_t *midi_output_count,
                               struct PluginNoteExpressionEvent *_note_expression_output,
                               size_t _note_expression_output_capacity,
                               size_t *note_expression_output_count);

/**
 * Clear queued MIDI and Note Expression output events.
 */
int plugin_clear_output_events(struct PluginHandle *handle);

/**
 * Queue one outgoing MIDI event for the next event-aware process call.
 */
int plugin_enqueue_midi_output_event(struct PluginHandle *handle, struct PluginMidiEvent event);

/**
 * Queue one outgoing Note Expression event for the next event-aware process call.
 */
int plugin_enqueue_note_expression_output_event(struct PluginHandle *handle,
                                                struct PluginNoteExpressionEvent event);

/**
 * Copy queued outgoing MIDI events without processing audio.
 */
int plugin_get_midi_output_events(struct PluginHandle *handle,
                                  struct PluginMidiEvent *out,
                                  size_t capacity,
                                  size_t *out_count);

/**
 * Copy queued outgoing Note Expression events without processing audio.
 */
int plugin_get_note_expression_output_events(struct PluginHandle *handle,
                                             struct PluginNoteExpressionEvent *out,
                                             size_t capacity,
                                             size_t *out_count);

/**
 * Get the number of parameters
 */
int plugin_get_parameter_count(const struct PluginHandle *handle);

/**
 * Get parameter info by index.
 *
 * # Returns
 * * Pointer to parameter info. The pointer is valid only while the
 *   `PluginHandle` used to obtain it remains alive and has not been destroyed.
 * * `NULL` if the handle is invalid or the index is out of bounds.
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 */
const struct ParameterInfo *plugin_get_parameter_info(const struct PluginHandle *handle,
                                                      size_t index);

/**
 * Set a parameter value (normalized 0.0-1.0).
 *
 * # Arguments
 * * `handle` - Plugin handle
 * * `param_id` - Parameter ID string
 * * `normalized_value` - Normalized value (0.0 = min, 1.0 = max)
 *
 * # Returns
 * * 0 on success
 * * Error code on failure
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `param_id` must be a valid, null-terminated UTF-8 C string that remains
 *   readable for the duration of this call.
 */
int plugin_set_parameter(struct PluginHandle *handle,
                         const char *param_id,
                         double normalized_value);

/**
 * Get a parameter value (normalized 0.0-1.0).
 *
 * # Returns
 * * Normalized value on success
 * * -1.0 on error
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `param_id` must be a valid, null-terminated UTF-8 C string that remains
 *   readable for the duration of this call.
 */
double plugin_get_parameter(const struct PluginHandle *handle, const char *param_id);

/**
 * Get plugin information as a JSON string.
 *
 * # Returns
 * * JSON string owned by the caller. It must be released with
 *   [`plugin_free_string`] when no longer needed.
 * * `NULL` on error.
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 */
char *plugin_get_info_json(const struct PluginHandle *handle);

/**
 * Free a string returned by the plugin.
 *
 * # Safety
 * * `s` must be either `NULL` or a pointer previously returned by a function
 *   documented as returning an owned string (for example [`plugin_get_info_json`],
 *   [`plugin_ffi_platform_info_json`], or [`plugin_suggest_preset_filename`]).
 * * The pointer must not be freed more than once.
 */
void plugin_free_string(char *s);

/**
 * Save plugin state to a JSON byte buffer.
 *
 * # Returns
 * * Pointer to an allocated buffer owned by the caller on success. It must be
 *   released with [`plugin_free_state`] when no longer needed.
 * * `NULL` on error.
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `out_len` must be a valid pointer to `usize` that this call may write.
 */
uint8_t *plugin_save_state(const struct PluginHandle *handle, size_t *out_len);

/**
 * Load plugin state from a JSON byte buffer.
 *
 * # Returns
 * * 0 on success
 * * Error code on failure
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `data` must point to `len` bytes of valid JSON that remain readable for
 *   the duration of this call.
 */
int plugin_load_state(struct PluginHandle *handle, const uint8_t *data, size_t len);

/**
 * Free a state buffer returned by [`plugin_save_state`] or
 * [`plugin_export_preset_json`].
 *
 * # Safety
 * * `data` must be either `NULL` or a pointer previously returned by a
 *   function documented as returning an owned byte buffer, with the same
 *   `len` value that was written to the associated `out_len` pointer.
 * * The pointer must not be freed more than once.
 */
void plugin_free_state(uint8_t *data, size_t len);

/**
 * Export a named preset document as JSON bytes.
 *
 * The returned buffer uses the preset document schema advertised by
 * [`plugin_preset_document_info`] and must be freed with [`plugin_free_state`].
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `preset_name` may be `NULL` or must be a valid, null-terminated UTF-8 C
 *   string that remains readable for the duration of this call.
 * * `out_len` must be a valid pointer to `usize` that this call may write.
 */
uint8_t *plugin_export_preset_json(const struct PluginHandle *handle,
                                   const char *preset_name,
                                   size_t *out_len);

/**
 * Import a JSON preset document created by [`plugin_export_preset_json`].
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `data` must point to `len` bytes of valid preset JSON that remain readable
 *   for the duration of this call.
 */
int plugin_import_preset_json(struct PluginHandle *handle, const uint8_t *data, size_t len);

/**
 * Suggest a filesystem-safe preset filename.
 *
 * # Returns
 * * Owned string that the caller must release with [`plugin_free_string`].
 * * `NULL` on error.
 *
 * # Safety
 * * `handle` must be a valid plugin handle that has not been destroyed.
 * * `preset_name` may be `NULL` or must be a valid, null-terminated UTF-8 C
 *   string that remains readable for the duration of this call.
 */
char *plugin_suggest_preset_filename(const struct PluginHandle *handle, const char *preset_name);

/**
 * Get the list of available plugin types as a JSON array string.
 *
 * # Returns
 * * JSON array string owned by the caller. It must be released with
 *   [`plugin_free_string`] when no longer needed.
 * * `NULL` on error.
 */
char *plugin_available_types(void);

#endif  /* SOTF_AUDIO_FFI_H */
