//! Captures the current Crossover parameters generated by the NIH fallback.

// Rust guideline compliant 2026-02-21
use crate::params::DynamicParams;
use crate::wrapper;
use nih_plug::prelude::Params;
use plugins_bridge::param_bridge::{BridgedParamInfo, BridgedParamKind, ParamBridge};
use sotf_host::plugin::Plugin;

fn default_native_infos() -> (Vec<BridgedParamInfo>, Box<dyn Plugin>) {
    let specs = wrapper::get_param_specs("Crossover");
    assert!(
        specs.is_empty(),
        "Crossover currently has no static NIH ParamSpec arm"
    );
    let bridge = ParamBridge::new(specs);
    let mut infos: Vec<_> = (0..bridge.count())
        .filter_map(|index| bridge.info(index))
        .collect();
    let plugin = plugins_bridge::create_plugin(
        "Crossover",
        wrapper::plugin_constructor_channels("Crossover"),
        48_000,
        &wrapper::default_plugin_config("Crossover"),
    )
    .unwrap();
    for parameter in plugin.parameters() {
        if infos.iter().any(|info| info.id == parameter.id.as_str()) {
            continue;
        }
        if let Some(info) = wrapper::bridged_info_from_parameter(&parameter) {
            infos.push(info);
        }
    }
    for info in &mut infos {
        info.id = wrapper::legacy_external_param_id("Crossover", &info.id).to_string();
    }
    (infos, plugin)
}

#[test]
fn current_crossover_native_metadata_and_saved_parameter_ids() {
    let (infos, _plugin) = default_native_infos();
    assert_eq!(infos.len(), 1);
    let frequency = &infos[0];
    assert_eq!(frequency.id, "frequency");
    assert_eq!(frequency.kind, BridgedParamKind::Float);

    let params = DynamicParams::from_infos(&infos);
    let entries = params.param_map();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].0, "frequency");
    let (_id, pointer, _group) = entries[0].clone();
    // SAFETY: `pointer` was returned by `params.param_map()` and `params` is
    // kept alive for every read below.
    let default_plain = unsafe { pointer.default_plain_value() };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let default_normalized = unsafe { pointer.default_normalized_value() };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let current_normalized = unsafe { pointer.unmodulated_normalized_value() };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let lower_plain = unsafe { pointer.preview_plain(0.0) };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let upper_plain = unsafe { pointer.preview_plain(1.0) };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let quarter_plain = unsafe { pointer.preview_plain(0.25) };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let midpoint_plain = unsafe { pointer.preview_plain(0.5) };
    // SAFETY: The pointer still refers to the live `params` allocation.
    let three_quarter_plain = unsafe { pointer.preview_plain(0.75) };
    let range_kind = if frequency.logarithmic {
        "FloatRange::Skewed(factor=-2.0)"
    } else {
        "FloatRange::Linear"
    };

    assert!((default_plain as f64 - frequency.default_value).abs() < 1.0e-4);
    assert!((default_normalized - current_normalized).abs() < 1.0e-6);
    for (normalized, plain) in [
        (0.0, lower_plain),
        (0.25, quarter_plain),
        (0.5, midpoint_plain),
        (0.75, three_quarter_plain),
        (1.0, upper_plain),
    ] {
        let expected =
            frequency.min_value + normalized * (frequency.max_value - frequency.min_value);
        assert!((f64::from(plain) - expected).abs() < 0.01);
    }
    println!(
        "native_param_count={};id={};name={};unit={};min={};max={};default={};logarithmic={};realtime={};nih_range={range_kind};default_normalized={default_normalized:.9};current_normalized={current_normalized:.9};normalized_0_plain={lower_plain:.6};normalized_25_plain={quarter_plain:.6};normalized_50_plain={midpoint_plain:.6};normalized_75_plain={three_quarter_plain:.6};normalized_1_plain={upper_plain:.6};state_field_id=frequency",
        infos.len(),
        frequency.id,
        frequency.name,
        frequency.unit,
        frequency.min_value,
        frequency.max_value,
        frequency.default_value,
        frequency.logarithmic,
        frequency.realtime,
    );
}

#[test]
fn current_native_fallback_omits_string_runtime_parameters() {
    let (infos, plugin) = default_native_infos();
    let runtime_ids: Vec<_> = plugin
        .parameters()
        .into_iter()
        .map(|parameter| parameter.id.to_string())
        .collect();
    assert_eq!(runtime_ids, ["type", "frequency", "mode"]);
    assert_eq!(
        infos
            .iter()
            .map(|info| info.id.as_str())
            .collect::<Vec<_>>(),
        ["frequency"]
    );
    println!(
        "native_runtime_ids={runtime_ids:?};native_published_ids={:?};static_spec_count={}",
        infos
            .iter()
            .map(|info| info.id.as_str())
            .collect::<Vec<_>>(),
        wrapper::get_param_specs("Crossover").len(),
    );
}
