[package]
name = "sotf-room-eq-graph"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
autoeq = { workspace = true }
serde_json = { workspace = true }
sotf-engine = { workspace = true }

[dev-dependencies]
sotf-plugins = { workspace = true }
